summary: "Cоздать вопрос"
description: "Cоздать вопрос"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  description: "other description"
  required: true
  schema:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example : 5
      text:
        type: "string"
        format: "str"
        example: "130+3"
      answers:
        type: "array[str]"
        example: ["133", "130", "1303"]
      correct:
        type: "integer"
        format: "int64"
        example: 0

responses:
  405:
    description: "Invalid input"